- group: local
  host1:
      host: 192.168.43.88
      user: testuser
      passwd: test123!
      database: test4
      
      
- group: mix
  member1:
      host: 35.154.61.189
      user: jvie
      passwd: "#jview@123"
      database: jdb
      
  member2: 
      host: 35.154.61.189
      user: loc
      passwd: loc@12345
      database: jdb
         
      
      
      
- group: remote
  member1:
      host: 35.154.61.189
      user: loc
      passwd: loc@12345
      database: test1
         
- group: aws
  member1:
      host: 35.154.61.189
      user: jvie
      passwd: "#jview@123"
      database: jdb

- group: psql
  member1:
      host: 35.154.61.189
      user: psqluser
      passwd: psqlroot
      database: testdb
      